#!/bin/sh /etc/rc.common
# Copyright (C) 2021 axelra.com

START=81

USE_PROCD=1

start_service() {
        procd_open_instance
        procd_set_param command /usr/sbin/example-upload -hs256 $TOKEN -port 8080 -base /www/nginx
        procd_set_param stdout 1 # forward stdout of the command to logd
        procd_set_param stderr 1 # same for stderr
        procd_set_param respawn
        procd_close_instance
}
